// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "testAppPlayground",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "testAppPlayground",
            targets: ["AppModule"],
            bundleIdentifier: "com.arose.testAppPlayground",
            teamIdentifier: "57QSDJBF5E",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-algorithms.git", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Algorithms", package: "swift-algorithms")
            ],
            path: "."
        )
    ]
)